config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path

from shop.apps import ShopConfig
from shop.views import category_products, ProductListView, CategoryListView, ProductCreateView, ProductDetailView, \
    ProductUpdateView, ProductDeleteView, BlogsListView, BlogsDetailView, BlogsUpdateView, BlogsDeleteView, \
    BlogsCreateView

app_name = ShopConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='list'),
    path('create/', ProductCreateView.as_view(), name='create'),
    path('create_blogs/', BlogsCreateView.as_view(), name='create_blogs'),
    path('category/', CategoryListView.as_view(), name='category'),
    path('<int:pk>/products/', category_products, name='category_products'),
    path('view/<int:pk>/', ProductDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', ProductUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', ProductDeleteView.as_view(), name='delete'),
    path('blogs/', BlogsListView.as_view(), name='list_blogs'),
    path('view_blogs/<int:pk>/', BlogsDetailView.as_view(), name='view_blogs'),
    path('edit_blogs/<int:pk>/', BlogsUpdateView.as_view(), name='edit_blogs'),
    path('delete_blogs/<int:pk>/', BlogsDeleteView.as_view(), name='delete_blogs'),

]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UserConfig
from users.views import RegisterView, ProfileView, generate_new_password, verify_email

app_name = UserConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/genpassword/', generate_new_password, name='generate_new_password'),
    path('verification/<str:email>', verify_email, name='verify_email'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')
    phone = models.CharField(max_length=35, verbose_name='телефон', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)
    country = models.CharField(max_length=50, verbose_name='страна', **NULLABLE)
    verify_code = models.CharField(max_length=100, verbose_name='код верификации', **NULLABLE)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

users/forms.py
from users.models import User
from django.contrib.auth.forms import UserChangeForm
from django import forms
from django.contrib.auth.forms import UserCreationForm


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2',)


class UserProfileForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'password', 'first_name', 'last_name', 'phone', 'avatar', 'country')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

users/views.py
import random
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.shortcuts import redirect, render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView
from users.forms import UserRegisterForm, UserProfileForm
from users.models import User


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'

    def get_success_url(self):
        return reverse('users:verify_email', kwargs={'email': self.object.email})

    def form_valid(self, form):
        self.object = form.save()
        if form.is_valid():
            verification_code = ''.join([str(random.randint(0, 9)) for _ in range(12)])
            self.object.verify_code = verification_code
            self.object.is_active = False
            self.object.save()
            send_mail(
                subject='Поздравляем с регистрацией',
                message=f'Вы зарегистрировались на нашей платформе, ваш код авторизации {verification_code}',
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=[self.object.email],
            )
        return super().form_valid(form)


class ProfileView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


@login_required
def generate_new_password(request):
    new_password = ''.join([str(random.randint(0, 9)) for _ in range(12)])
    send_mail(
        subject='Вы сменили пароль',
        message=f'Ващ новый пароль: {new_password}',
        from_email=settings.EMAIL_HOST_USER,
        recipient_list=[request.user.email]
    )
    request.user.set_password(new_password)
    request.user.save()
    return redirect(reverse('shop:list'))


def verify_email(request, email):
    if request.method == 'POST':
        code = request.POST.get('user-code')
        user = User.objects.get(email=email)
        if user.verify_code == code:
            user.is_active = True
            user.save()
            return redirect(reverse('shop:list'))
    return render(request, 'users/verification.html')

users/templates/users/acc_active_email.html
{% autoescape off %} 
Hi {{ user.username }}, 
Please click on the link to confirm your registration, 
http://{{ domain }}{% url 'activate' uidb64=uid token=token %} 
{% endautoescape %}

users/templates/users/login.html
{% extends 'shop/base.html' %}

    {% block content %}
<div class="col-12">

    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Вход
                    </h3>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Войти</button>

                </div>
            <div class="card-footer"></div>
        </div>
    </div>
    </form>
  </div>

    {% endblock %}

users/templates/users/register.html
{% extends 'shop/base.html' %}

    {% block content %}
<div class="col-12">

    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Регистрация
                    </h3>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Регистрация</button>

                </div>
            <div class="card-footer"></div>
        </div>
    </div>
    </form>
  </div>

    {% endblock %}

users/templates/users/success.html
<h1>Congratulations, you have been successfully verified!</h1>

users/templates/users/user_form.html
{% extends 'shop/base.html' %}

    {% block content %}
<div class="col-12">

    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Профиль
                    </h3>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Сохранить</button>

                </div>
            <div class="card-footer">
                <a href ="{% url 'users:generate_new_password' %}" class="btn btn-danger">Сгенерировать пароль</a>
            </div>
        </div>
    </div>
     </form>
  </div>

    {% endblock %}

users/templates/users/verification.html
<div class="row">
    <div class="col-3">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <h4 class="my-0 font_weight-normal">Проверка почты</h4>
           </div>
            <div class="card-body">
                <form method="post" action="" class="form-floating">
                    {%  csrf_token  %}
                    <div class="mb-3">
                        <label for="user_code">Код подтверждения</label>
                        <input
                                type="text"
                                name="user-code"
                                class="form-control"
                                id="user-code"
                                placeholder="Код подтверждения" required>
                    </div>
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary" href="{% url 'users:login' %}">Подтвердить</button>
                </form>
            </div>
        </div>
        </div>
    </div>
</div>