config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path

from shop.apps import ShopConfig
from shop.views import category_products, ProductListView, CategoryListView, ProductCreateView, ProductDetailView, \
    ProductUpdateView, ProductDeleteView, BlogsListView, BlogsDetailView, BlogsUpdateView, BlogsDeleteView, \
    BlogsCreateView

app_name = ShopConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='list'),
    path('create/', ProductCreateView.as_view(), name='create'),
    path('create_blogs/', BlogsCreateView.as_view(), name='create_blogs'),
    path('category/', CategoryListView.as_view(), name='category'),
    path('<int:pk>/products/', category_products, name='category_products'),
    path('view/<int:pk>/', ProductDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', ProductUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', ProductDeleteView.as_view(), name='delete'),
    path('blogs/', BlogsListView.as_view(), name='list_blogs'),
    path('view_blogs/<int:pk>/', BlogsDetailView.as_view(), name='view_blogs'),
    path('edit_blogs/<int:pk>/', BlogsUpdateView.as_view(), name='edit_blogs'),
    path('delete_blogs/<int:pk>/', BlogsDeleteView.as_view(), name='delete_blogs'),

]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UserConfig
from users.views import RegisterView, ProfileView, generate_new_password, verify_email

app_name = UserConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/genpassword/', generate_new_password, name='generate_new_password'),
    path('verification/<str:email>', verify_email, name='verify_email'),
]

shop/models.py
from django.conf import settings
from django.db import models

from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    objects = None
    name = models.CharField(max_length=150, verbose_name='наименование')
    description = models.CharField(max_length=150, **NULLABLE, verbose_name='описание')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Версия продукта', **NULLABLE)

    def __str__(self):
        # Строковое отображение объекта
        return f'{self.name}'

    class Meta:
        verbose_name = 'Категория'  # Настройка для наименования одного объекта
        verbose_name_plural = 'Категории'  # Настройка для наименования набора объектов
        ordering = ('name',)


class Product(models.Model):
    objects = None
    name = models.CharField(max_length=150, verbose_name='наименование')
    description = models.CharField(max_length=150, verbose_name='описание')
    image_preview = models.ImageField(upload_to='image', height_field=None, width_field=None, max_length=100,
                                      **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория', **NULLABLE)
    purchase_price = models.IntegerField('цена за покупку')
    date_creation = models.DateField(max_length=150, verbose_name='дата создания')
    date_last_mod = models.DateField(max_length=150, verbose_name='дата последнего изменения')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='владелец')
    is_published = models.BooleanField(default=False, verbose_name='признак публикации')

    def __str__(self):
        # Строковое отображение объекта
        return f'{self.name}'

    class Meta:
        verbose_name = 'Товар'  # Настройка для наименования одного объекта
        verbose_name_plural = 'Товары'  # Настройка для наименования набора объектов
        permissions = [
            (
                'set_published',
                'Can publish posts'
            ),
        ]


class Blogs(models.Model):
    objects = None
    title = models.CharField(max_length=150, verbose_name='наименование')
    slug = models.CharField(max_length=150, verbose_name='slug', null=True, blank=True)
    content = models.CharField(max_length=150, verbose_name='содержимое')
    image_preview = models.ImageField(upload_to='image_blogs', height_field=None, width_field=None, max_length=1,
                                      **NULLABLE)
    creation_date = models.DateField(max_length=150, verbose_name='дата создания')
    publication_attribute = models.BooleanField(default=True, verbose_name='признак публикации')
    number_of_views = models.IntegerField(default=0, verbose_name='количество просмотров')

    def __str__(self):
        # Строковое отображение объекта
        return f'{self.title}'

    class Meta:
        verbose_name = 'Блог'  # Настройка для наименования одного объекта
        verbose_name_plural = 'Блоги'  # Настройка для наименования набора объектов


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='продукт')
    num_of_version = models.IntegerField(default=1, verbose_name='номер текущей версии', unique=True, **NULLABLE)
    name_version = models.CharField(max_length=150, verbose_name='название версии')
    flag_of_version = models.BooleanField(default=True, verbose_name='признак версии')

    def __str__(self):
        # Строковое отображение объекта
        return f'{self.product} {self.name_version}'

    class Meta:
        verbose_name = 'Версия'  # Настройка для наименования одного объекта
        verbose_name_plural = 'Версии'  # Настройка для наименования набора объектов

shop/forms.py
from django import forms

from shop.models import Product, Version


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        exclude = ('owner',)

    def clean_name(self):
        cleaned_data = self.cleaned_data['name']
        taboo_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']
        for i in taboo_words:
            if i in cleaned_data:
                raise forms.ValidationError('Содержится запрещенный продукт')

        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data['description']
        taboo_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']
        for i in taboo_words:
            if i in cleaned_data:
                raise forms.ValidationError('Содержится запрещенный продукт')

        return cleaned_data


class VersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

        def clean_product(self):
            cleaned_data = self.cleaned_data['product']
            taboo_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                           'радар']
            for i in taboo_words:
                if i in cleaned_data:
                    raise forms.ValidationError('Содержится запрещенный продукт')

            return cleaned_data

shop/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.cache import cache
from django.forms import inlineformset_factory
from django.urls import reverse_lazy, reverse
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from pytils.translit import slugify

from shop.forms import ProductForm, VersionForm
from shop.models import Product, Category, Blogs, Version
from shop.services import get_cached_category_list


class CategoryListView(LoginRequiredMixin, ListView):
    model = Category
    template_name = 'shop/category.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['categories'] = get_cached_category_list
        return context_data


@login_required
def category_products(request, pk):
    category_item = Category.objects.get(pk=pk)
    context = {
        'object_list': Product.objects.filter(category_id=pk),
        'title': f'Категория - {category_item.name}'
    }
    return render(request, 'shop/products.html', context)


class ProductListView(LoginRequiredMixin, ListView):
    model = Product
    template_name = 'shop/products.html'

    def get_queryset(self):
        return super().get_queryset().filter(is_published=True)


class BlogsListView(LoginRequiredMixin, ListView):
    model = Blogs
    template_name = 'shop/blogs.html'

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(publication_attribute=True)
        return queryset


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('shop:list')

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()

        return super().form_valid(form)


class BlogsCreateView(LoginRequiredMixin, CreateView):
    model = Blogs
    fields = '__all__'
    success_url = reverse_lazy('shop:list_blogs')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()

        return super().form_valid(form)


class ProductDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = Product
    permission_required = 'shop.view_product'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        if settings.CACHE_ENABLE:
            key = f'version_list_{self.object.pk}'
            version_list = cache.get(key)
            if version_list is None:
                version_list = self.object.version_set.all()
                cache.set(key, version_list)
        else:
            version_list = self.object.version_set.all()

        context_data['versions'] = version_list
        return context_data


class BlogsDetailView(LoginRequiredMixin, DetailView):
    model = Blogs

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.number_of_views += 1
        self.object.save()
        return self.object


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('shop:list')

    def get_queryset(self):
        return super().get_queryset().filter(owner=self.request.user)

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFromset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFromset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFromset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)


class BlogsUpdateView(LoginRequiredMixin, UpdateView):
    model = Blogs
    fields = '__all__'

    # success_url = reverse_lazy('shop:list_blogs')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('shop:view_blogs', args=[self.kwargs.get('pk')])


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    fields = '__all__'
    success_url = reverse_lazy('shop:list')


class BlogsDeleteView(LoginRequiredMixin, DeleteView):
    model = Blogs
    fields = '__all__'
    success_url = reverse_lazy('shop:list_blogs')


class VersionCreateView(LoginRequiredMixin, CreateView):
    model = Version

    def form_valid(self, form):
        product_pk = self.kwargs['pk']  # Получаем pk продукта из URL
        product = Product.objects.get(pk=product_pk)  # Получаем объект продукта
        form.instance.product = product  # Устанавливаем продукт в поле версии
        return super().form_valid(form)

shop/templates/shop/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
{% include 'shop/includes/inc_shop_menu.html' %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title }}</h1>
    <p class="lead">Добро пожаловать в наш магазин!</p>
</div>
{% block content %}
{% endblock %}
        </div>
    </div>
</div>
</body>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</html>

shop/templates/shop/blogs.html
{% extends 'shop/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container text-center" xmlns="">
    <a href="{% url 'shop:create_blogs' %}"  type="button" class="btn btn-lg btn-block btn-outline-primary">Добавить блог</a>
     {% for object in object_list %}
    <div class="row">
        <div class="col">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object }}</h4>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3 ">
                        <li><img src="{{ object.image_preview|mymedia }}" class="img-fluid"/></li>
                    </ul>
                    <a href="{% url 'shop:view_blogs' object.pk %}"  type="button" class="btn btn-lg btn-block btn-outline-primary">Описание</a>
                    <a href="{% url 'shop:delete_blogs' object.pk %}"  type="button" class="btn btn-lg btn-block btn-outline-primary">Удалить</a>
                    <a href="{% url 'shop:edit_blogs' object.pk %}"  type="button" class="btn btn-lg btn-block btn-outline-primary">Изменить</a>
                </div>
            </div>
            {% endfor %}
   {% endblock %}

shop/templates/shop/blogs_confirm_delete.html
{% extends 'shop/base.html' %}

    {% block content %}
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить блог "{{ object.title }}?"</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'shop:list_blogs' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>

    {% endblock %}

shop/templates/shop/blogs_detail.html
{% extends 'shop/base.html' %}

    {% block content %}
        <div class="col-12">
            <div class="row">

                <div class="col-6">
                    <div class="card">
                      <div class="card-header">
                        <h3 class="card-title">
                          Информация о блоге
                        </h3>
                      </div>
                 <div class="card-body">
                   <table class="table">
                     <tr>
                       <td>Содержимое</td>
                       <td>{{ object.content }}</td>
                     </tr>
                     <tr>
                       <td>Дата создания</td>
                       <td>{{ object.creation_date }}</td>
                     </tr><tr>
                       <td>Slug</td>
                       <td>{{ object.slug }}</td>
                     </tr>
                   </table>
                </div>
                      <div class="card-footer"></div>
                        Просмотры {{ object.number_of_views }}
                  </div>
                  </div>
            </div>
        </div>

    {% endblock %}

shop/templates/shop/blogs_form.html
{% extends 'shop/base.html' %}

    {% block content %}
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                                Сохранить
                            {% else %}
                                Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    {% endblock %}

shop/templates/shop/category.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Товары</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
{% include 'shop/includes/inc_shop_menu.html' %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title }}</h1>
</div>
<div class="container text-center" xmlns="">
     {% for object in object_list %}
    <div class="row">
        <div class="col">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object }}</h4>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3 ">
                    </ul>
                    <a href="{% url 'shop:category_products' object.pk %}"  type="button" class="btn btn-lg btn-block btn-outline-primary">К товарам</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
</body>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</html>

shop/templates/shop/product_confirm_delete.html
{% extends 'shop/base.html' %}

    {% block content %}
{% if request.user.is_authenticated %}
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Хотите удалить товар "{{ object.title }}?"</p>
                            <button type="submit" class="btn btn-danger">Подтвердить</button>
                            <a href="{% url 'shop:list' %}" class="btn btn-warning">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
{% else %}
    <div class="col-12">
            <form class="row-3">
                <div class="col-3">
                    <div class="card">
   <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Войти</a>
   <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Зарегистрироваться</a>
{% endif %}
    {% endblock %}

shop/templates/shop/product_detail.html
{% extends 'shop/base.html' %}

    {% block content %}
{% if request.user.is_authenticated %}
            <div class="col-12">
                <div class="row">

                    <div class="col-6">
                        <div class="card">
                          <div class="card-header">
                            <h3 class="card-title">
                              Информация о товаре
                            </h3>
                          </div>
                     <div class="card-body">
                       <table class="table">
                         <tr>
                           <td>Категория товара</td>
                           <td>{{ object.category }}</td>
                         </tr>
                         <tr>
                           <td>Цена</td>
                           <td>{{ object.purchase_price }}$</td>
                         </tr>
                         <tr>
                           <td>Описание</td>
                           <td>{{ object.description }}</td>
                         </tr>
                       </table>
                    </div>
                          <div class="card-footer"></div>
                      </div>
                      </div>
                    <div class="col-6">
                        <div class="card">
                          <div class="card-header">
                            <h3 class="card-title">
                              Версии продукта
                                </h3>
                              </div>
                            <div class="card-body">
                            <ul>
                            {% for version in versions %}
                                <li>{{ version }}</li>
                            {% endfor %}
                            </ul>
                            </div>
                            <div class="card-footer"></div>
                </div>
            </div>
{% else %}
    <div class="col-12">
            <form class="row-3">
                <div class="col-3">
                    <div class="card">
   <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Войти</a>
   <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Зарегистрироваться</a>
{% endif %}
                        {% endblock %}

shop/templates/shop/product_form.html
{% extends 'shop/base.html' %}

    {% block content %}
{% if request.user.is_authenticated %}
    <div class="col-12">

        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Добавление продукта
                        </h3>
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-success">
                                {% if object %}
                                    Сохранить
                                {% else %}
                                    Создать
                                {% endif %}
                            </button>
                    </div>
                </div>
            </div>
        </div>
              <div class="col-6">
                  <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Версии продукта
                        </h3>
                        </div>
                        <div class="card-body">
                         {{ formset.management_form }}
                         {% for form in formset.forms %}
                            {{ form.as_p }}
                            {% if not formloop.last %}
                                <hr>
                            {% endif %}
                         {% endfor %}
                    </div>
                  <div class="card-footer"></div>
              </div>
         </form>
      </div>
{% else %}
    <div class="col-12">
            <form class="row-3">
                <div class="col-3">
                    <div class="card">
   <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Войти</a>
   <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Зарегистрироваться</a>
{% endif %}
{% endblock %}

shop/templates/shop/products.html
{% extends 'shop/base.html' %}
{% load my_tags %}
{% block content %}
{% if request.user.is_authenticated %}
    <div class="container text-center" xmlns="">
        <div class="col-12 mb-5">
           <a class="btn btn-outline-primary" href="{% url 'shop:create' %}"  type="button" class="btn btn-lg btn-block btn-outline-primary">Добавить товар</a>
            {% for object in object_list %}
        <div class="row">
            <div class="col">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ object }}</h4>
                    </div>
                    <div class="card-body">
                        <ul class="list-unstyled mt-3 mb-4 text-start m-3 ">
                            <li><img src="{{ object.image_preview|mymedia }}" class="img-fluid"/></li>
                        </ul>
                        <a href="{% url 'shop:view' object.pk %}"  type="button" class="btn btn-lg btn-block btn-outline-primary">Описание</a>
                        <a href="{% url 'shop:delete' object.pk %}"  type="button" class="btn btn-lg btn-block btn-outline-primary">Удалить</a>
                        <a href="{% url 'shop:edit' object.pk %}"  type="button" class="btn btn-lg btn-block btn-outline-primary">Изменить</a>
                    </div>
                </div>
                {% endfor %}
                {% else %}
    <div class="col-12">
            <form class="row-3">
                <div class="col-3">
                    <div class="card">
   <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Войти</a>
   <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Зарегистрироваться</a>
{% endif %}
   {% endblock %}